# Generated by Django 4.0.5 on 2022-06-08 11:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import northbridge.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required. Between 2 and 30 characters.Cannot start or end with a space.No special symbols outside of accented letters.', max_length=30, validators=[django.core.validators.RegexValidator('^\\w[\\w ]*\\w+$', 'Enter a valid name. At least 2 characters, cannot start or end with a space.No special symbols outside of accented letters.', 'invalid')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=northbridge.models._create_hash_id, max_length=10, unique=True)),
                ('start_date', models.DateTimeField()),
                ('state', models.CharField(choices=[('P', 'Pending'), ('A', 'Active'), ('E', 'Expired')], default='P', max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_policy', to='northbridge.user')),
            ],
        ),
    ]
