# Generated by Django 4.0.5 on 2022-06-08 11:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('northbridge', '0002_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='visits_page', to='northbridge.page')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='visits_policy', to='northbridge.policy')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
